# Generated by Django 5.1.5 on 2025-04-23 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Haber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("icerik", models.TextField()),
                (
                    "yayin_tarihi",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                ("yazar", models.CharField(max_length=100)),
                ("kategori", models.CharField(max_length=50)),
                (
                    "resim",
                    models.ImageField(
                        blank=True, null=True, upload_to="haber_resimleri/"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Haberler",
            },
        ),
    ]
