# Generated by Django 5.1.5 on 2025-04-24 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "haberler",
            "0003_alter_haber_options_haber_yayinda_kategori_aciklama_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="haber",
            name="goruntulenme_sayisi",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Görüntülenme Sayısı"
            ),
        ),
        migrations.CreateModel(
            name="Yorum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icerik", models.TextField()),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                ("aktif", models.BooleanField(default=True)),
                (
                    "haber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yorumlar",
                        to="haberler.haber",
                    ),
                ),
                (
                    "yazar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
    ]
