# Generated by Django 5.1.5 on 2025-04-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0004_haber_goruntulenme_sayisi_yorum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="haber",
            options={},
        ),
        migrations.AlterModelOptions(
            name="yorum",
            options={},
        ),
        migrations.RemoveField(
            model_name="haber",
            name="yayinda",
        ),
        migrations.RemoveField(
            model_name="kategori",
            name="aciklama",
        ),
        migrations.RemoveField(
            model_name="kategori",
            name="icon",
        ),
        migrations.AddField(
            model_name="haber",
            name="aktif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="haber",
            name="ozet",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="kategori",
            name="aktif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kategori",
            name="guncelleme_tarihi",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="kategori",
            name="olusturulma_tarihi",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="haber",
            name="goruntulenme_sayisi",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="haber",
            name="kategori",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="haberler.kategori"
            ),
        ),
        migrations.AlterField(
            model_name="haber",
            name="resim",
            field=models.ImageField(
                default="haberler/default.jpg", upload_to="haberler/"
            ),
        ),
        migrations.AlterField(
            model_name="haber",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="kategori",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
