# Generated by Django 5.1.5 on 2025-04-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0005_alter_haber_options_alter_yorum_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="haber",
            options={"ordering": ["-yayin_tarihi"], "verbose_name_plural": "Haberler"},
        ),
        migrations.AlterModelOptions(
            name="yorum",
            options={"ordering": ["-olusturulma_tarihi"]},
        ),
        migrations.RemoveField(
            model_name="haber",
            name="aktif",
        ),
        migrations.RemoveField(
            model_name="haber",
            name="ozet",
        ),
        migrations.RemoveField(
            model_name="kategori",
            name="aktif",
        ),
        migrations.RemoveField(
            model_name="kategori",
            name="guncelleme_tarihi",
        ),
        migrations.RemoveField(
            model_name="kategori",
            name="olusturulma_tarihi",
        ),
        migrations.AddField(
            model_name="haber",
            name="yayinda",
            field=models.BooleanField(default=True, verbose_name="Yayında"),
        ),
        migrations.AddField(
            model_name="kategori",
            name="aciklama",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kategori",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Bootstrap Icons sınıf adı (örn: newspaper, trophy)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="haber",
            name="goruntulenme_sayisi",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Görüntülenme Sayısı"
            ),
        ),
        migrations.AlterField(
            model_name="haber",
            name="kategori",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="haberler",
                to="haberler.kategori",
            ),
        ),
        migrations.AlterField(
            model_name="haber",
            name="resim",
            field=models.ImageField(
                blank=True, null=True, upload_to="haber_resimleri/"
            ),
        ),
        migrations.AlterField(
            model_name="haber",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="kategori",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
