# Generated by Django 5.1.5 on 2025-04-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0006_alter_haber_options_alter_yorum_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="haber",
            name="ozet",
            field=models.TextField(
                blank=True,
                help_text="Haberin kısa özeti (maksimum 500 karakter)",
                max_length=500,
            ),
        ),
    ]
