# Generated by Django 5.1.5 on 2025-04-24 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0007_haber_ozet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haber",
            name="yayin_tarihi",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Haberin yayınlanacağı tarih ve saat",
            ),
        ),
    ]
