# Generated by Django 5.1.5 on 2025-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0008_alter_haber_yayin_tarihi"),
    ]

    operations = [
        migrations.AddField(
            model_name="haber",
            name="manset",
            field=models.BooleanField(
                default=False,
                help_text="Bu haber manşette gösterilsin mi?",
                verbose_name="Manşet Haber",
            ),
        ),
    ]
