# Generated by Django 5.1.5 on 2025-04-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0009_haber_manset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ilan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firma_adi",
                    models.CharField(max_length=200, verbose_name="Firma Adı"),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "faaliyet_alani",
                    models.CharField(max_length=200, verbose_name="Faaliyet Alanı"),
                ),
                ("aciklama", models.TextField(verbose_name="İlan Açıklaması")),
                ("adres", models.TextField(verbose_name="Adres")),
                ("telefon", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Web Sitesi")),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        help_text="Facebook sayfa URL'i",
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        help_text="Instagram profil URL'i",
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        help_text="Twitter profil URL'i",
                        verbose_name="Twitter",
                    ),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True,
                        help_text="YouTube kanal URL'i",
                        verbose_name="YouTube",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profil/şirket URL'i",
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ilan_logolari/",
                        verbose_name="Firma Logosu",
                    ),
                ),
                (
                    "fotograf1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ilan_fotograflari/",
                        verbose_name="Fotoğraf 1",
                    ),
                ),
                (
                    "fotograf2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ilan_fotograflari/",
                        verbose_name="Fotoğraf 2",
                    ),
                ),
                (
                    "fotograf3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ilan_fotograflari/",
                        verbose_name="Fotoğraf 3",
                    ),
                ),
                (
                    "konum_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Enlem",
                    ),
                ),
                (
                    "konum_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Boylam",
                    ),
                ),
                (
                    "olusturulma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "bitis_tarihi",
                    models.DateTimeField(
                        help_text="İlanın yayında kalacağı son tarih",
                        verbose_name="İlan Bitiş Tarihi",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("pasif", "Pasif"),
                            ("beklemede", "Onay Bekliyor"),
                        ],
                        default="beklemede",
                        max_length=10,
                        verbose_name="İlan Durumu",
                    ),
                ),
                (
                    "one_cikarilmis",
                    models.BooleanField(
                        default=False,
                        help_text="Bu ilan öne çıkarılsın mı?",
                        verbose_name="Öne Çıkarılmış",
                    ),
                ),
                (
                    "goruntulenme_sayisi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Görüntülenme Sayısı"
                    ),
                ),
                (
                    "ekleyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ilanlar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ekleyen",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ilanlar",
                        to="haberler.kategori",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "İlanlar",
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
    ]
