# Generated by Django 5.1.5 on 2025-04-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0010_ilan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ilan",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="fotograf1",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="fotograf2",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="fotograf3",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="kategori",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="konum_latitude",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="konum_longitude",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="ilan",
            name="youtube",
        ),
    ]
