# Generated by Django 5.1.5 on 2025-05-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0011_remove_ilan_facebook_remove_ilan_fotograf1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haber",
            name="resim",
            field=models.ImageField(
                blank=True,
                help_text="Ana haber resmi",
                null=True,
                upload_to="haber_resimleri/",
            ),
        ),
        migrations.CreateModel(
            name="HaberFotograf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resim", models.ImageField(upload_to="haber_resimleri/")),
                ("baslik", models.CharField(blank=True, max_length=100)),
                ("sira", models.PositiveIntegerField(default=0)),
                (
                    "haber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotograflar",
                        to="haberler.haber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haber Fotoğrafı",
                "verbose_name_plural": "Haber Fotoğrafları",
                "ordering": ["sira"],
            },
        ),
    ]
