# Generated by Django 5.1.5 on 2025-05-02 19:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0012_alter_haber_resim_haberfotograf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haber",
            name="icerik",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Haber içeriği ve görseller buraya eklenebilir",
                verbose_name="İçerik",
            ),
        ),
        migrations.AlterField(
            model_name="haber",
            name="resim",
            field=models.ImageField(
                blank=True, null=True, upload_to="haber_resimleri/"
            ),
        ),
        migrations.DeleteModel(
            name="HaberFotograf",
        ),
    ]
