# Generated by Django 5.1.5 on 2025-05-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0013_alter_haber_icerik_alter_haber_resim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haber",
            name="icerik",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="AltBaslik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Alt Başlık")),
                ("icerik", models.TextField(verbose_name="Alt Başlık İçeriği")),
                (
                    "siralama",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "haber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alt_basliklar",
                        to="haberler.haber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alt Başlık",
                "verbose_name_plural": "Alt Başlıklar",
                "ordering": ["siralama"],
            },
        ),
        migrations.CreateModel(
            name="IcerikResmi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resim",
                    models.ImageField(
                        upload_to="haber_icerik_resimleri/", verbose_name="İçerik Resmi"
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resim Açıklaması"
                    ),
                ),
                (
                    "siralama",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "haber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icerik_resimleri",
                        to="haberler.haber",
                    ),
                ),
            ],
            options={
                "verbose_name": "İçerik Resmi",
                "verbose_name_plural": "İçerik Resimleri",
                "ordering": ["siralama"],
            },
        ),
    ]
