# Generated by Django 5.1.5 on 2025-05-02 20:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0014_alter_haber_icerik_altbaslik_icerikresmi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="icerikresmi",
            name="haber",
        ),
        migrations.AlterField(
            model_name="haber",
            name="icerik",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="İçerik"
            ),
        ),
        migrations.DeleteModel(
            name="AltBaslik",
        ),
        migrations.DeleteModel(
            name="IcerikResmi",
        ),
    ]
