# Generated by Django 5.1.5 on 2025-05-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0015_remove_icerikresmi_haber_alter_haber_icerik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="haber",
            name="kaynak_url",
            field=models.URLField(blank=True, null=True, verbose_name="Orijinal URL"),
        ),
        migrations.AddField(
            model_name="haber",
            name="otomatik_eklendi",
            field=models.BooleanField(default=False, verbose_name="Otomatik Eklendi"),
        ),
        migrations.CreateModel(
            name="HaberKaynagi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
                ("url", models.URLField(verbose_name="Kaynak URL")),
                ("aktif", models.BooleanField(default=True)),
                (
                    "aranan_kelimeler",
                    models.TextField(
                        blank=True,
                        help_text="Aramak istediğiniz anahtar kelimeleri virgülle ayırarak yazın. Boş bırakırsanız tüm haberler çekilir.",
                    ),
                ),
                ("son_kontrol", models.DateTimeField(blank=True, null=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haber_kaynaklari",
                        to="haberler.kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haber Kaynağı",
                "verbose_name_plural": "Haber Kaynakları",
            },
        ),
        migrations.AddField(
            model_name="haber",
            name="kaynak",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="haberler",
                to="haberler.haberkaynagi",
            ),
        ),
    ]
